### ISSUE TITLE
Unrecognized extended object attributes

### ISSUE THREAD

**Issue by orirmi** [mvantellingen/python-zeep#549]
I have an xsd type that extends another one, and the attributes of the second one are not recognized. 
I have added wsdl file and python code gists to reproduce the issue. Simply run ``python repro.py test.wsdl``, and you should get a traceback ending with

```
TypeError: {http://www.exm.com/abc/efg/hijkl}Model() got an unexpected keyword argument 'Creator'. Signature: `Id: xsd:string`
```

WSDL: https://gist.github.com/orirmi/867f81e6e80567651663eb0013c14479
PYTHON: https://gist.github.com/orirmi/f0e2e1b2a1d25c507bb8037668d059fa

The WSDL itself is stripped down version of a bigger one. Unfortunately, I didn't manage to minimize or clean it up even further, since the code starts working at some point.

Python is 2.7.12, commit hash of Zeep I am using is 6dce326fec564ab0026b4a3dcfc1b9e5df14bccf. Note that the similar code used to work with zeep 1.1.0 version.

Can you please look into it?

**Comment by mvantellingen** [comment]
The error seems to be valid I think? Model extends Block which only defines an Id element

**Comment by orirmi** [comment]
Looks like I was too eager when minimizing the example. I will upload another one asap.
