### ISSUE TITLE
bug (4.2.0): New __del__ method in transport.py

### ISSUE THREAD

**Issue by danielfajt** [mvantellingen/python-zeep#1347]
The version of zeep: **4.2.0**

After the upgrade from 4.1.0 > 4.2.0 there is an error following each successful request:

```python
Exception ignored in: <function Transport.__del__ at 0x7f9d829c7c40>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zeep/transports.py", line 159, in __del__
    if self.__close_session:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AsyncTransport' object has no attribute '_Transport__close_session'
Exception ignored in: <function Transport.__del__ at 0x7f9d829c7c40>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zeep/transports.py", line 159, in __del__
AttributeError: 'AsyncTransport' object has no attribute '_Transport__close_session'
```

There is no **self.__close_session** on **AsyncTransport** class.

Thanks for you work!

**Comment by theStygianArchitect** [comment]
Any word on when this will hit pypi?
